---
# This playbook sets up etherpad-lite on a server.
# pass the hosts to install to as an extra variable
- hosts: all
  user: root
  tasks:
  - name: Install dumb init
    get_url:
      dest: /usr/bin/dumb-init
      url: https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64
      mode: 0775
      validate_certs: no
  - name: Install epel
    package: name=epel-release state=installed 


- hosts: mariadb
  user: root
  tasks:
  - name: Add mysql repo
    copy:
      content: |
        [mysql57-community]
        name=MySQL 5.7 Community Server
        baseurl=http://repo.mysql.com/yum/mysql-5.7-community/el/6/$basearch/
        enabled=1
        gpgcheck=0
      dest: /etc/yum.repos.d/mysql.repo

  - name: Install required software packages
    package: name={{ item }} state=installed 
    with_items:
    - mysql-community-server
    - mysql-community-client
    - python-devel
    - python-pip
    - mysql-devel
    - git
    - gcc
    - libabw
    - curl
    - nodejs

  - name: install mysql
    command: pip install mysql-python

  - name: initialize mysql
    remote_user: mysql
    command: mysqld --initialize-insecure
    ignore_errors: true

  - name: start mysqld
    remote_user: mysql
    command: mysqld
    async: 300

  - name: create etherpad-lite database
    mysql_db: name={{ db_name }} encoding=utf8 state=present
    ignore_errors: true

  - name: create etherpad-lite mysql user
    mysql_user: name={{ db_user }} password={{ db_password }} priv={{ db_name }}.*:ALL state=present
    ignore_errors: true

  - name: make mysql super insecure
    copy:
      content: |
        [mysqld]
        skip-grant-tables
      dest: /etc/my.cnf

- hosts: etherpad
  user: root
  tasks:
  - name: Install required software packages
    package: name={{ item }} state=installed 
    with_items:
    - git
    - gcc
    - libabw
    - curl
    - python-devel
    - python-pip
    - nodejs

  - name: create etherpad-lite user
    user: name=etherpad-lite shell=/bin/bash

  - name: lock etherpad-lite user's password
    command: passwd -l etherpad-lite

  - name: check out etherpad-lite code
    git: repo=https://github.com/ether/etherpad-lite.git dest=/opt/etherpad-lite version={{ etherpad_version }}

  - name: create log directory
    file: path=/var/log/etherpad-lite owner=etherpad-lite group=etherpad-lite state=directory

  - name: create etherpad-lite startup script
    template: src=templates/etc_init_etherpad-lite.j2 dest=/etc/init.d/etherpad-lite mode=0755

  - name: configure etherpad-lite
    template: src=templates/opt_etherpad-lite_settings.json.j2 dest=/opt/etherpad-lite/settings.json mode=0640 owner=etherpad-lite group=etherpad-lite

  - name: update permissions for etherpad-lite directory
    file: path=/opt/etherpad-lite owner=etherpad-lite group=etherpad-lite recurse=yes state=directory


- hosts: nginx
  user: root
  tasks:
  - name: Add nginx repo
    copy:
      content: |
        [nginx]
        name=nginx repo
        baseurl=http://nginx.org/packages/centos/7/$basearch/
        gpgcheck=0
        enabled=1
      dest: /etc/yum.repos.d/nginx.repo

  - name: Install required software packages
    package: name={{ item }} state=installed 
    with_items:
    - nginx

  - name: configure nginx to forward http traffic to etherpad-lite
    template: src=templates/etc_nginx_sites-available_default.j2 dest=/etc/nginx/conf.d/default.conf
